bundle_name: mix_series_parallel
description: null
version: 0.0.1
image: null
libraries: null
system_dependencies: null
environment: null
commands: null
blocks:
- name: ReplaceChar
  file_name: mix_srs_prl
  class_name: ReplaceChar
  label: ReplaceChar
  description: ''
  tags: []
  libraries: []
  executors:
    name: ProcessExecutor
  inputs:
  - name: in_ds
    dataFlowType: series
    dataType: Any
    render_type: null
    default: null
    doc: null
    label: null
  outputs:
  - name: out_ds
    dataFlowType: series
    dataType: Any
    doc: null
    label: null
    transport:
      is_series:
      - true
      name: null
      topic: null
      sender_port: null
      receiver_port: null
      queue_size: 0
      has_initialized: false
  defaultExecutionMode: ProcessExecutor
  source:
    module_name: mix_series_parallel
- name: DeReplaceChar
  file_name: mix_srs_prl
  class_name: DeReplaceChar
  label: DeReplaceChar
  description: ''
  tags: []
  libraries: []
  executors:
    name: ProcessExecutor
  inputs:
  - name: in_ds
    dataFlowType: series
    dataType: Any
    render_type: null
    default: null
    doc: null
    label: null
  outputs:
  - name: out_ds
    dataFlowType: series
    dataType: Any
    doc: null
    label: null
    transport:
      is_series:
      - true
      name: null
      topic: null
      sender_port: null
      receiver_port: null
      queue_size: 0
      has_initialized: false
  defaultExecutionMode: ProcessExecutor
  source:
    module_name: mix_series_parallel
- name: PrintReplaceFreq
  file_name: mix_srs_prl
  class_name: PrintReplaceFreq
  label: PrintReplaceFreq
  description: ''
  tags: []
  libraries: []
  executors:
    name: ProcessExecutor
  inputs:
  - name: s_in_ds
    dataFlowType: series
    dataType: Any
    render_type: null
    default: null
    doc: null
    label: null
  - name: l_in_ds
    dataFlowType: series
    dataType: Any
    render_type: null
    default: null
    doc: null
    label: null
  outputs:
  - name: s_out_ds
    dataFlowType: series
    dataType: Any
    doc: null
    label: null
    transport:
      is_series:
      - true
      name: null
      topic: null
      sender_port: null
      receiver_port: null
      queue_size: 0
      has_initialized: false
  - name: l_out_ds
    dataFlowType: series
    dataType: Any
    doc: null
    label: null
    transport:
      is_series:
      - true
      name: null
      topic: null
      sender_port: null
      receiver_port: null
      queue_size: 0
      has_initialized: false
  defaultExecutionMode: ProcessExecutor
  source:
    module_name: mix_series_parallel
category: MixSeriesParallel
