bundle_name: bundle
description: null
version: 0.0.1
image: null
libraries: null
system_dependencies: null
environment: null
commands: null
blocks:
- name: Stream to Pandas
  file_name: stream_to_pandas_df
  class_name: DataQueueToPandasDf_PythonStream
  label: Stream to Pandas
  description: Converts data queue to pandas dataframe
  tags:
  - kafkatopandas
  - streamtopandas
  - dataqueuetopandas
  - kafka
  - queue
  - pandas
  - stream
  libraries: []
  executors:
    name: ProcessExecutor
  inputs:
  - name: input_stream
    dataFlowType: series
    dataType: List[list]
    render_type: null
    default: null
    doc: data queue from the previous stream block
    label: input_stream
  - name: input_schema
    dataFlowType: atomic
    dataType: json
    render_type: null
    default: {}
    doc: data schema from the previous stream block
    label: input_schema
  outputs:
  - name: df
    dataFlowType: atomic
    dataType: DataFrame
    doc: null
    label: df
    transport:
      is_series:
      - false
      name: null
      topic: null
      sender_port: null
      receiver_port: null
      queue_size: 0
      has_initialized: false
  defaultExecutionMode: ProcessExecutor
  source:
    module_name: bundle
- name: LinearRegression
  file_name: regressor
  class_name: LinearRegression
  label: LinearRegression
  description: LinearRegression
  tags:
  - ML models
  libraries: []
  executors:
    name: ProcessExecutor
  inputs:
  - name: fit_intercept
    dataFlowType: atomic
    dataType: boolean
    render_type: null
    default: true
    doc: null
    label: fit_intercept
  - name: normalize
    dataFlowType: atomic
    dataType: boolean
    render_type: null
    default: false
    doc: null
    label: normalize
  - name: copy_X
    dataFlowType: atomic
    dataType: boolean
    render_type: null
    default: true
    doc: null
    label: copy_X
  - name: n_jobs
    dataFlowType: atomic
    dataType: json
    render_type: null
    default:
      n_jobs: '[None]'
    doc: null
    label: n_jobs
  - name: operation
    dataFlowType: atomic
    dataType: string
    render_type: null
    default: model_instance
    doc: fit, predict, score, evaluate, model_instance, get_params, set_params
    label: operation
  - name: attribute
    dataFlowType: atomic
    dataType: string
    render_type: null
    default: ''
    doc: coef_, rank_, singular_, intercept_
    label: attribute
  - name: x_data
    dataFlowType: atomic
    dataType: Any
    render_type: null
    default: {}
    doc: null
    label: x_data
  - name: y_data
    dataFlowType: atomic
    dataType: Any
    render_type: null
    default: {}
    doc: null
    label: y_data
  - name: test_x_data
    dataFlowType: atomic
    dataType: Any
    render_type: null
    default: {}
    doc: null
    label: test_x_data
  - name: test_y_data
    dataFlowType: atomic
    dataType: Any
    render_type: null
    default: {}
    doc: null
    label: test_y_data
  - name: metric_function
    dataFlowType: atomic
    dataType: array
    render_type: null
    default:
    - r2_score
    doc: null
    label: metric_function
  - name: path
    dataFlowType: atomic
    dataType: string
    render_type: null
    default: ''
    doc: null
    label: path
  - name: load
    dataFlowType: atomic
    dataType: boolean
    render_type: null
    default: false
    doc: null
    label: load
  - name: save
    dataFlowType: atomic
    dataType: boolean
    render_type: null
    default: false
    doc: null
    label: save
  - name: params
    dataFlowType: atomic
    dataType: json
    render_type: null
    default: {}
    doc: null
    label: params
  outputs:
  - name: predictions
    dataFlowType: atomic
    dataType: Any
    doc: null
    label: null
    transport:
      is_series:
      - false
      name: null
      topic: null
      sender_port: null
      receiver_port: null
      queue_size: 0
      has_initialized: false
  - name: model_attributes
    dataFlowType: atomic
    dataType: Any
    doc: null
    label: null
    transport:
      is_series:
      - false
      name: null
      topic: null
      sender_port: null
      receiver_port: null
      queue_size: 0
      has_initialized: false
  defaultExecutionMode: ProcessExecutor
  source:
    module_name: bundle
- name: CsvProjectSpaceReader_PythonStream
  file_name: csv_reader
  class_name: CsvProjectSpaceReader_PythonStream
  label: CsvProjectSpaceReader_PythonStream
  description: To read csv/text files from project space
  tags:
  - bigdata
  - project space
  - reader
  - csv/text
  libraries: []
  executors:
    name: ProcessExecutor
  inputs:
  - name: input_file_path
    dataFlowType: atomic
    dataType: string
    render_type: null
    default: ''
    doc: path to the file to be read
    label: input_file_path
  - name: batch_size
    dataFlowType: atomic
    dataType: integer
    render_type: null
    default: 10000
    doc: number of lines to be read in single iteration
    label: batch size
  - name: parse_dates
    dataFlowType: atomic
    dataType: array
    render_type: null
    default: []
    doc: date columns to be parsed to standard python datetime format as an array
    label: parse dates
  - name: date_parser
    dataFlowType: atomic
    dataType: string
    render_type: null
    default: ''
    doc: custom date format of the date columns in standard python datetime format
    label: date parser standard
  - name: limit
    dataFlowType: atomic
    dataType: integer
    render_type: null
    default: -1
    doc: total number of rows to read default is -1 and it will read entire data on
      default value
    label: limit
  outputs:
  - name: output_stream
    dataFlowType: series
    dataType: List[list]
    doc: null
    label: output_stream
    transport:
      is_series: true
      name: null
      topic: null
      sender_port: null
      receiver_port: null
      queue_size: 0
      has_initialized: false
  - name: output_schema
    dataFlowType: atomic
    dataType: json
    doc: null
    label: output_schema
    transport:
      is_series: false
      name: null
      topic: null
      sender_port: null
      receiver_port: null
      queue_size: 0
      has_initialized: false
  defaultExecutionMode: ProcessExecutor
  source:
    module_name: bundle
- name: SklearnMLFeeder
  file_name: sklearn_ml_feeder
  class_name: SklearnMLFeeder
  label: SklearnMLFeeder
  description: Sklearn ML feeder from pandas to numpy x and y
  tags:
  - SklearnMLFeeder
  - getdata
  - mlfeeder
  - sklearndata
  libraries: []
  executors:
    name: ProcessExecutor
  inputs:
  - name: x_columns
    dataFlowType: atomic
    dataType: array
    render_type: null
    default: []
    doc: null
    label: x_columns
  - name: y_column
    dataFlowType: atomic
    dataType: string
    render_type: null
    default: ''
    doc: null
    label: y_column
  - name: df
    dataFlowType: atomic
    dataType: DataFrame
    render_type: null
    default: null
    doc: pandas dataframe input
    label: input_df
  outputs:
  - name: out_x
    dataFlowType: atomic
    dataType: ndarray
    doc: null
    label: null
    transport:
      is_series:
      - false
      name: null
      topic: null
      sender_port: null
      receiver_port: null
      queue_size: 0
      has_initialized: false
  - name: out_y
    dataFlowType: atomic
    dataType: ndarray
    doc: null
    label: null
    transport:
      is_series:
      - false
      name: null
      topic: null
      sender_port: null
      receiver_port: null
      queue_size: 0
      has_initialized: false
  - name: feature_names
    dataFlowType: atomic
    dataType: array
    doc: null
    label: null
    transport:
      is_series:
      - false
      name: null
      topic: null
      sender_port: null
      receiver_port: null
      queue_size: 0
      has_initialized: false
  defaultExecutionMode: ProcessExecutor
  source:
    module_name: bundle
category: test
