bundle_name: series_socket
description: null
version: 0.0.1
image: null
libraries: null
system_dependencies: null
environment: null
commands: null
blocks:
- name: STDIn_series
  file_name: sr_socket
  class_name: STDIn_series
  label: STDIn_series
  description: ''
  tags: []
  libraries: []
  executors:
    name: ProcessExecutor
  inputs:
  - name: filename
    dataFlowType: atomic
    dataType: string
    render_type: null
    default: ''
    doc: null
    label: null
  - name: records
    dataFlowType: atomic
    dataType: integer
    render_type: null
    default: 0
    doc: null
    label: null
  outputs:
  - name: out_ds
    dataFlowType: series
    dataType: Any
    doc: null
    label: null
    transport:
      is_series:
      - true
      name: null
      topic: null
      sender_port: null
      receiver_port: null
      queue_size: 0
      has_initialized: false
  defaultExecutionMode: ProcessExecutor
  source:
    module_name: series_socket
- name: STDOut_series
  file_name: sr_socket
  class_name: STDOut_series
  label: STDOut_series
  description: ''
  tags: []
  libraries: []
  executors:
    name: ProcessExecutor
  inputs:
  - name: in_ds
    dataFlowType: series
    dataType: Any
    render_type: null
    default: null
    doc: null
    label: null
  - name: out_filename
    dataFlowType: atomic
    dataType: string
    render_type: null
    default: ''
    doc: null
    label: null
  outputs: []
  defaultExecutionMode: ProcessExecutor
  source:
    module_name: series_socket
category: SeriesSocket
