bundle_name: FloatType
description: null
version: 0.0.1
image: null
libraries: null
system_dependencies: null
environment: null
commands: null
blocks:
- name: Float
  file_name: float
  class_name: FloatType
  label: Float
  description: ''
  tags: []
  libraries: []
  executors:
    name: ProcessExecutor
  inputs:
  - name: a
    dataFlowType: atomic
    dataType: float
    render_type: null
    default: 0.0
    doc: null
    label: null
  outputs: []
  defaultExecutionMode: ProcessExecutor
  source:
    module_name: FloatType
category: Float
