bundle_name: stdout_mix_series_parallel
description: null
version: 0.0.1
image: null
libraries: null
system_dependencies: null
environment: null
commands: null
blocks:
- name: STDOut
  file_name: STDOut_mix_srs_prl
  class_name: STDOut
  label: STDOut
  description: ''
  tags: []
  libraries: []
  executors:
    name: ProcessExecutor
  inputs:
  - name: in_ds
    dataFlowType: series
    dataType: Any
    render_type: null
    default: null
    doc: null
    label: null
  - name: out_filename
    dataFlowType: atomic
    dataType: string
    render_type: null
    default: ''
    doc: null
    label: null
  outputs: []
  defaultExecutionMode: ProcessExecutor
  source:
    module_name: stdout_mix_series_parallel
category: STDOut_MIX_SERIES_PARALLEL
