bundle_name: memory
description: null
version: 0.0.1
image: null
libraries: null
system_dependencies: null
environment: null
commands: null
blocks:
- name: STDIn_socket
  file_name: socket
  class_name: STDIn
  label: STDIn_socket
  description: ''
  tags: []
  libraries: []
  executors:
    name: ProcessExecutor
    resource_requirements:
      cores: 1
      memory: 1024
      gpu: 0
      gpu_is_optional: true
      max_servers_count: 1
      number_of_instances: 1
  inputs:
  - name: filename
    dataFlowType: atomic
    dataType: string
    render_type: null
    default: ''
    doc: null
    label: null
  outputs:
  - name: out_ds
    dataFlowType: atomic
    dataType: Any
    doc: null
    label: null
    transport:
      is_series:
      - false
      name: null
      topic: null
      sender_port: null
      receiver_port: null
      queue_size: 0
      has_initialized: false
  defaultExecutionMode: ProcessExecutor
  source:
    module_name: memory
- name: STDOut_socket
  file_name: socket
  class_name: STDOut
  label: STDOut_socket
  description: ''
  tags: []
  libraries: []
  executors:
    name: ProcessExecutor
    resource_requirements:
      cores: 1
      memory: 1024
      gpu: 0
      gpu_is_optional: true
      max_servers_count: 1
      number_of_instances: 1
  inputs:
  - name: in_ds
    dataFlowType: atomic
    dataType: Any
    render_type: null
    default: null
    doc: null
    label: null
  - name: out_filename
    dataFlowType: atomic
    dataType: string
    render_type: null
    default: ''
    doc: null
    label: null
  outputs: []
  defaultExecutionMode: ProcessExecutor
  source:
    module_name: memory
category: MemoryTransport
