---
id: "6ce62b88-7677-45d6-8147-b4cbb012ce48"
name: "Fb_ad_analytics"
description: "A project to perform ad analytics on FB data"
imageId: "b0cc81051dbf5078538e6b575294dde6e3d80f8cb8509879b917fabb8ac07713"
addedBy: "8e81119e-0abd-42ac-af6c-df6841cc469c"
addedOn: "Wed Mar 10 14:09:11 GMT 2021"
updatedBy: "8e81119e-0abd-42ac-af6c-df6841cc469c"
updatedOn: "Wed Mar 10 14:09:11 GMT 2021"
buildImageReqd: false
base_image: "gcr.io/razorthink-gcp-pre-prod/aios-images:10.4.4"
base_image_version: "10.4.4"
base_image_libraries:
  triggeredOn: "2021-03-11 00:23:56.876"
  pip_packages:
  - name: "razor-api"
    version: "0.0.1"
  - name: "razor-fs"
    version: "0.0.1"
  - name: "razor-ds"
    version: "0.0.1"
  - name: "rzt-dl"
    version: "4.0.0"
  - name: "model-designer-parser"
    version: "4.0.0"
  - name: "razor-flow"
    version: "2.0.0"
  - name: "cloudpickle"
    version: ">=1.3.0"
  - name: "boto3"
    version: "<1.16"
  - name: "pandas"
    version: ">=1.1.4"
  - name: "pysftp"
    version: ">=0.2.9"
  - name: "requests"
    version: "==2.23.0"
  - name: "hdfs"
    version: ">=2.5.8"
  - name: "requests_kerberos"
    version: ">=0.12.0"
  - name: "typeguard"
    version: "==2.2.2"
  - name: "typing-extensions"
    version: ""
  - name: "pygit2"
    version: ">=1.2.1"
  - name: "azure-storage-blob"
    version: ">=12.5.0"
  - name: "google-cloud-storage"
    version: "==1.32.0"
  - name: "pyyaml"
    version: ">=5.3.1"
  - name: "pyzmq"
    version: ">=19.0.0"
  - name: "networkx"
    version: ">=2.4"
  - name: "pygraphviz"
    version: ">=1.5"
  - name: "pydot"
    version: ">=1.4.1"
  - name: "IPython"
    version: ">=7.13.0"
  - name: "altair"
    version: ">=4.1.0"
  - name: "scikit-learn"
    version: ">=0.22.1"
  - name: "scipy"
    version: "==1.4.1"
  - name: "tblib"
    version: ">=1.6.0"
  - name: "pyspark"
    version: "==3.0"
  - name: "SQLAlchemy"
    version: "==1.3.20"
  - name: "PyMySQL"
    version: "==0.10.1"
  - name: "snowflake-sqlalchemy"
    version: "==1.2.4"
  - name: "pyodbc"
    version: "==4.0.30"
  - name: "smart-open"
    version: "==4.1.2"
  - name: "fastapi"
    version: "==0.63.0"
  - name: "semantic_version"
    version: "==2.8.5"
  - name: "cx_Oracle"
    version: "==8.1.0"
  - name: "sasl"
    version: "==0.2.1"
  - name: "thrift"
    version: "==0.13.0"
  - name: "thrift_sasl"
    version: "==0.4.2"
  - name: "pyhive"
    version: "==0.6.3"
  - name: "impyla"
    version: "==0.16.3"
  - name: "flask"
    version: "==1.1.2"
  - name: "numpy"
    version: "==1.19.5"
  - name: "ipywidgets"
    version: "==7.6.3"
  - name: "walkdir"
    version: "==0.4.1"
  - name: "python-multipart"
    version: "==0.0.5"
  - name: "ipykernel"
    version: "==5.4.3"
  - name: "pynacl"
    version: "==1.4.0"
  - name: "watchdog"
    version: ""
  - name: "psutil"
    version: ""
  - name: "cloudpickle"
    version: ">=1.3.0"
  - name: "boto3"
    version: "<1.16"
  - name: "pandas"
    version: ">=1.1.4"
  - name: "pysftp"
    version: ">=0.2.9"
  - name: "requests"
    version: "==2.23.0"
  - name: "hdfs"
    version: ">=2.5.8"
  - name: "requests_kerberos"
    version: ">=0.12.0"
  - name: "typeguard"
    version: "==2.2.2"
  - name: "typing-extensions"
    version: ""
  - name: "pygit2"
    version: ">=1.2.1"
  - name: "azure-storage-blob"
    version: ">=12.5.0"
  - name: "google-cloud-storage"
    version: "==1.32.0"
  - name: "pyyaml"
    version: ">=5.3.1"
  - name: "pyzmq"
    version: ">=19.0.0"
  - name: "networkx"
    version: ">=2.4"
  - name: "pygraphviz"
    version: ">=1.5"
  - name: "pydot"
    version: ">=1.4.1"
  - name: "IPython"
    version: ">=7.13.0"
  - name: "altair"
    version: ">=4.1.0"
  - name: "scikit-learn"
    version: ">=0.22.1"
  - name: "scipy"
    version: "==1.4.1"
  - name: "tblib"
    version: ">=1.6.0"
  - name: "pyspark"
    version: "==3.0"
  - name: "SQLAlchemy"
    version: "==1.3.20"
  - name: "PyMySQL"
    version: "==0.10.1"
  - name: "snowflake-sqlalchemy"
    version: "==1.2.4"
  - name: "pyodbc"
    version: "==4.0.30"
  - name: "smart-open"
    version: "==4.1.2"
  - name: "fastapi"
    version: "==0.63.0"
  - name: "semantic_version"
    version: "==2.8.5"
  - name: "cx_Oracle"
    version: "==8.1.0"
  - name: "sasl"
    version: "==0.2.1"
  - name: "thrift"
    version: "==0.13.0"
  - name: "thrift_sasl"
    version: "==0.4.2"
  - name: "pyhive"
    version: "==0.6.3"
  - name: "impyla"
    version: "==0.16.3"
  - name: "flask"
    version: "==1.1.2"
  - name: "numpy"
    version: "==1.19.5"
  - name: "ipywidgets"
    version: "==7.6.3"
  - name: "walkdir"
    version: "==0.4.1"
  - name: "python-multipart"
    version: "==0.0.5"
  - name: "ipykernel"
    version: "==5.4.3"
  - name: "pynacl"
    version: "==1.4.0"
  - name: "watchdog"
    version: ""
  - name: "psutil"
    version: ""
  - name: "cloudpickle"
    version: ">=1.3.0"
  - name: "pyzmq"
    version: ">=19.0.0"
  - name: "networkx"
    version: ">=2.4"
  - name: "pydot"
    version: ">=1.4.1"
  - name: "boto3"
    version: ">=1.12.35"
  - name: "pysftp"
    version: ">=0.2.9"
  - name: "requests"
    version: ">=2.23.0"
  - name: "hdfs"
    version: ">=2.5.8"
  - name: "IPython"
    version: ">=7.13.0"
  - name: "altair"
    version: ">=4.1.0"
  - name: "tblib"
    version: ">=1.6.0"
  - name: "typeguard"
    version: ">=2.2.2"
  - name: "pynacl"
    version: ""
  - name: "pygit2"
    version: ">=1.2.1"
  - name: "watchdog"
    version: ""
  - name: "psutil"
    version: ""
  - name: "pyyaml"
    version: "==5.3.1"
  - name: "munch"
    version: "==2.5.0"
  - name: "typeguard"
    version: "==2.7.1"
  - name: "networkx"
    version: "==2.5"
  system_packages: []
  environment_variables:
  - id: null
    variable: "LD_LIBRARY_PATH"
    type: "String"
    value: "/usr/local/cuda/extras/CUPTI/lib64:/usr/local/cuda/lib64:"
    origin: null
    description: null
  - id: null
    variable: "LANG"
    type: "String"
    value: "C.UTF-8"
    origin: null
    description: null
  - id: null
    variable: "NODE_OPTIONS"
    type: "String"
    value: "NODE_OPTIONS --max_old_space_size=2048"
    origin: null
    description: null
  - id: null
    variable: "SHELL"
    type: "String"
    value: "/bin/bash"
    origin: null
    description: null
project_libraries:
  published_packages: []
  pip_packages:
  - id: "0e9ef941-95e9-4eb5-b2c6-f55e9e5cd098"
    name: "xlrd"
    version: "1.2.0"
    type: "PIP"
    updated_by: "8e81119e-0abd-42ac-af6c-df6841cc469c"
    updated_on: "Thu Mar 11 06:06:38 GMT 2021"
    added_by: "8e81119e-0abd-42ac-af6c-df6841cc469c"
    added_on: "Thu Mar 11 04:36:08 GMT 2021"
  - id: "c74cd2bc-cbab-4da6-badb-47b03e298058"
    name: "matplotlib"
    version: "3.3.4"
    type: "PIP"
    updated_by: "8e81119e-0abd-42ac-af6c-df6841cc469c"
    updated_on: "Thu Mar 11 05:06:07 GMT 2021"
    added_by: "8e81119e-0abd-42ac-af6c-df6841cc469c"
    added_on: "Thu Mar 11 05:06:07 GMT 2021"
  - id: "e035454a-0c0a-4500-91a2-fa55ec663330"
    name: "category-encoders"
    version: "2.2.2"
    type: "PIP"
    updated_by: "8e81119e-0abd-42ac-af6c-df6841cc469c"
    updated_on: "Thu Mar 11 05:23:51 GMT 2021"
    added_by: "8e81119e-0abd-42ac-af6c-df6841cc469c"
    added_on: "Thu Mar 11 05:23:51 GMT 2021"
  - id: "66e6b337-125a-459e-b31f-e5dca8921053"
    name: "xgboost"
    version: "1.3.3"
    type: "PIP"
    updated_by: "8e81119e-0abd-42ac-af6c-df6841cc469c"
    updated_on: "Thu Mar 11 05:24:15 GMT 2021"
    added_by: "8e81119e-0abd-42ac-af6c-df6841cc469c"
    added_on: "Thu Mar 11 05:24:15 GMT 2021"
  - id: "d479033f-4350-4f7c-9069-4471e0201c72"
    name: "shap"
    version: "0.39.0"
    type: "PIP"
    updated_by: "8e81119e-0abd-42ac-af6c-df6841cc469c"
    updated_on: "Thu Mar 11 05:24:43 GMT 2021"
    added_by: "8e81119e-0abd-42ac-af6c-df6841cc469c"
    added_on: "Thu Mar 11 05:24:43 GMT 2021"
  - id: "c277d63d-2a09-457f-bd05-baa4b4304b16"
    name: "scikit-learn"
    version: "0.24.1"
    type: "PIP"
    updated_by: "8e81119e-0abd-42ac-af6c-df6841cc469c"
    updated_on: "Thu Mar 11 05:26:26 GMT 2021"
    added_by: "8e81119e-0abd-42ac-af6c-df6841cc469c"
    added_on: "Thu Mar 11 05:26:26 GMT 2021"
  system_packages: []
environment_variables: []
