---
id: "4e5f8d1c-b9a6-4128-b5f9-078c9c4007f0"
name: "Sparse_Encoding_Jenoptik"
imageId: "6e717608f563ca3d3ad211cafd575ecd4e242e91700b29f76cfdcccf918eef0b"
addedBy: "ab3faaf2-fe6f-429d-9a06-5f807d7911e4"
addedOn: "Thu Mar 11 19:08:08 GMT 2021"
updatedBy: "ab3faaf2-fe6f-429d-9a06-5f807d7911e4"
updatedOn: "Thu Mar 11 19:08:08 GMT 2021"
buildImageReqd: false
base_image: "gcr.io/razorthink-gcp-pre-prod/aios-images:10.4.5"
base_image_version: "10.4.5"
base_image_libraries:
  triggeredOn: "2021-03-12 00:30:08.389"
  pip_packages:
  - name: "razor-api"
    version: "0.0.1"
  - name: "razor-fs"
    version: "0.0.1"
  - name: "razor-ds"
    version: "0.0.1"
  - name: "rzt-dl"
    version: "4.0.0"
  - name: "model-designer-parser"
    version: "4.0.0"
  - name: "razor-flow"
    version: "2.0.0"
  - name: "cloudpickle"
    version: ">=1.3.0"
  - name: "boto3"
    version: "<1.16"
  - name: "pandas"
    version: ">=1.1.4"
  - name: "pysftp"
    version: ">=0.2.9"
  - name: "requests"
    version: "==2.23.0"
  - name: "hdfs"
    version: ">=2.5.8"
  - name: "requests_kerberos"
    version: ">=0.12.0"
  - name: "typeguard"
    version: "==2.2.2"
  - name: "typing-extensions"
    version: ""
  - name: "pygit2"
    version: ">=1.2.1"
  - name: "azure-storage-blob"
    version: ">=12.5.0"
  - name: "google-cloud-storage"
    version: "==1.32.0"
  - name: "pyyaml"
    version: ">=5.3.1"
  - name: "pyzmq"
    version: ">=19.0.0"
  - name: "networkx"
    version: ">=2.4"
  - name: "pygraphviz"
    version: ">=1.5"
  - name: "pydot"
    version: ">=1.4.1"
  - name: "IPython"
    version: ">=7.13.0"
  - name: "altair"
    version: ">=4.1.0"
  - name: "scikit-learn"
    version: ">=0.22.1"
  - name: "scipy"
    version: "==1.4.1"
  - name: "tblib"
    version: ">=1.6.0"
  - name: "pyspark"
    version: "==3.0"
  - name: "SQLAlchemy"
    version: "==1.3.20"
  - name: "PyMySQL"
    version: "==0.10.1"
  - name: "snowflake-sqlalchemy"
    version: "==1.2.4"
  - name: "pyodbc"
    version: "==4.0.30"
  - name: "smart-open"
    version: "==4.1.2"
  - name: "fastapi"
    version: "==0.63.0"
  - name: "semantic_version"
    version: "==2.8.5"
  - name: "cx_Oracle"
    version: "==8.1.0"
  - name: "sasl"
    version: "==0.2.1"
  - name: "thrift"
    version: "==0.13.0"
  - name: "thrift_sasl"
    version: "==0.4.2"
  - name: "pyhive"
    version: "==0.6.3"
  - name: "impyla"
    version: "==0.16.3"
  - name: "flask"
    version: "==1.1.2"
  - name: "numpy"
    version: "==1.19.5"
  - name: "ipywidgets"
    version: "==7.6.3"
  - name: "walkdir"
    version: "==0.4.1"
  - name: "python-multipart"
    version: "==0.0.5"
  - name: "ipykernel"
    version: "==5.4.3"
  - name: "pynacl"
    version: "==1.4.0"
  - name: "watchdog"
    version: ""
  - name: "psutil"
    version: ""
  - name: "cloudpickle"
    version: ">=1.3.0"
  - name: "boto3"
    version: "<1.16"
  - name: "pandas"
    version: ">=1.1.4"
  - name: "pysftp"
    version: ">=0.2.9"
  - name: "requests"
    version: "==2.23.0"
  - name: "hdfs"
    version: ">=2.5.8"
  - name: "requests_kerberos"
    version: ">=0.12.0"
  - name: "typeguard"
    version: "==2.2.2"
  - name: "typing-extensions"
    version: ""
  - name: "pygit2"
    version: ">=1.2.1"
  - name: "azure-storage-blob"
    version: ">=12.5.0"
  - name: "google-cloud-storage"
    version: "==1.32.0"
  - name: "pyyaml"
    version: ">=5.3.1"
  - name: "pyzmq"
    version: ">=19.0.0"
  - name: "networkx"
    version: ">=2.4"
  - name: "pygraphviz"
    version: ">=1.5"
  - name: "pydot"
    version: ">=1.4.1"
  - name: "IPython"
    version: ">=7.13.0"
  - name: "altair"
    version: ">=4.1.0"
  - name: "scikit-learn"
    version: ">=0.22.1"
  - name: "scipy"
    version: "==1.4.1"
  - name: "tblib"
    version: ">=1.6.0"
  - name: "pyspark"
    version: "==3.0"
  - name: "SQLAlchemy"
    version: "==1.3.20"
  - name: "PyMySQL"
    version: "==0.10.1"
  - name: "snowflake-sqlalchemy"
    version: "==1.2.4"
  - name: "pyodbc"
    version: "==4.0.30"
  - name: "smart-open"
    version: "==4.1.2"
  - name: "fastapi"
    version: "==0.63.0"
  - name: "semantic_version"
    version: "==2.8.5"
  - name: "cx_Oracle"
    version: "==8.1.0"
  - name: "sasl"
    version: "==0.2.1"
  - name: "thrift"
    version: "==0.13.0"
  - name: "thrift_sasl"
    version: "==0.4.2"
  - name: "pyhive"
    version: "==0.6.3"
  - name: "impyla"
    version: "==0.16.3"
  - name: "flask"
    version: "==1.1.2"
  - name: "numpy"
    version: "==1.19.5"
  - name: "ipywidgets"
    version: "==7.6.3"
  - name: "walkdir"
    version: "==0.4.1"
  - name: "python-multipart"
    version: "==0.0.5"
  - name: "ipykernel"
    version: "==5.4.3"
  - name: "pynacl"
    version: "==1.4.0"
  - name: "watchdog"
    version: ""
  - name: "psutil"
    version: ""
  - name: "cloudpickle"
    version: ">=1.3.0"
  - name: "pyzmq"
    version: ">=19.0.0"
  - name: "networkx"
    version: ">=2.4"
  - name: "pydot"
    version: ">=1.4.1"
  - name: "boto3"
    version: ">=1.12.35"
  - name: "pysftp"
    version: ">=0.2.9"
  - name: "requests"
    version: ">=2.23.0"
  - name: "hdfs"
    version: ">=2.5.8"
  - name: "IPython"
    version: ">=7.13.0"
  - name: "altair"
    version: ">=4.1.0"
  - name: "tblib"
    version: ">=1.6.0"
  - name: "typeguard"
    version: ">=2.2.2"
  - name: "pynacl"
    version: ""
  - name: "pygit2"
    version: ">=1.2.1"
  - name: "watchdog"
    version: ""
  - name: "psutil"
    version: ""
  - name: "pyyaml"
    version: "==5.3.1"
  - name: "munch"
    version: "==2.5.0"
  - name: "typeguard"
    version: "==2.7.1"
  - name: "networkx"
    version: "==2.5"
  system_packages: []
  environment_variables:
  - id: null
    variable: "LD_LIBRARY_PATH"
    type: "String"
    value: "/usr/local/cuda/extras/CUPTI/lib64:/usr/local/cuda/lib64:"
    origin: null
    description: null
  - id: null
    variable: "LANG"
    type: "String"
    value: "C.UTF-8"
    origin: null
    description: null
  - id: null
    variable: "NODE_OPTIONS"
    type: "String"
    value: "NODE_OPTIONS --max_old_space_size=2048"
    origin: null
    description: null
  - id: null
    variable: "SHELL"
    type: "String"
    value: "/bin/bash"
    origin: null
    description: null
project_libraries:
  published_packages: []
  pip_packages:
  - id: "5f8319ea-b6c8-49e7-97b2-a4001cf88d27"
    name: "opencv-python"
    version: "4.5.1.48"
    type: "PIP"
    updated_by: "ab3faaf2-fe6f-429d-9a06-5f807d7911e4"
    updated_on: "Fri Mar 12 06:42:15 GMT 2021"
    added_by: "ab3faaf2-fe6f-429d-9a06-5f807d7911e4"
    added_on: "Fri Mar 12 06:42:15 GMT 2021"
  - id: "dd3be1f6-785d-48a5-9717-bddf4c38727c"
    name: "tqdm"
    version: "4.59.0"
    type: "PIP"
    updated_by: "ab3faaf2-fe6f-429d-9a06-5f807d7911e4"
    updated_on: "Fri Mar 12 07:26:52 GMT 2021"
    added_by: "ab3faaf2-fe6f-429d-9a06-5f807d7911e4"
    added_on: "Fri Mar 12 07:26:52 GMT 2021"
  - id: "94d38063-ea08-4048-bb06-b27072ded344"
    name: "scikit-image"
    version: "0.18.1"
    type: "PIP"
    updated_by: "ab3faaf2-fe6f-429d-9a06-5f807d7911e4"
    updated_on: "Fri Mar 12 08:31:43 GMT 2021"
    added_by: "ab3faaf2-fe6f-429d-9a06-5f807d7911e4"
    added_on: "Fri Mar 12 08:31:43 GMT 2021"
  - id: "58b83f66-e8b9-43ce-87f4-2de35f701e78"
    name: "matplotlib"
    version: "3.3.4"
    type: "PIP"
    updated_by: "ab3faaf2-fe6f-429d-9a06-5f807d7911e4"
    updated_on: "Fri Mar 12 08:50:58 GMT 2021"
    added_by: "ab3faaf2-fe6f-429d-9a06-5f807d7911e4"
    added_on: "Fri Mar 12 08:50:58 GMT 2021"
  - id: "398ff4b0-1ba4-4090-984b-5d9e823b14e1"
    name: "torch"
    version: "1.8.0"
    type: "PIP"
    updated_by: "ab3faaf2-fe6f-429d-9a06-5f807d7911e4"
    updated_on: "Fri Mar 12 08:51:25 GMT 2021"
    added_by: "ab3faaf2-fe6f-429d-9a06-5f807d7911e4"
    added_on: "Fri Mar 12 08:51:25 GMT 2021"
  - id: "ad27ca9c-6e03-4b97-96fc-ca1e7e199cf1"
    name: "torchvision"
    version: "0.9.0"
    type: "PIP"
    updated_by: "ab3faaf2-fe6f-429d-9a06-5f807d7911e4"
    updated_on: "Fri Mar 12 08:51:46 GMT 2021"
    added_by: "ab3faaf2-fe6f-429d-9a06-5f807d7911e4"
    added_on: "Fri Mar 12 08:51:46 GMT 2021"
  - id: "7785446a-8284-4067-aa2f-a3e94f950a15"
    name: "PyYAML"
    version: "5.4.1"
    type: "PIP"
    updated_by: "ab3faaf2-fe6f-429d-9a06-5f807d7911e4"
    updated_on: "Fri Mar 12 08:52:35 GMT 2021"
    added_by: "ab3faaf2-fe6f-429d-9a06-5f807d7911e4"
    added_on: "Fri Mar 12 08:52:35 GMT 2021"
  system_packages: []
environment_variables: []
