bundle_name: print_replace_freq_single
description: null
version: 0.0.1
image: null
libraries: null
system_dependencies: null
environment: null
commands: null
blocks:
- name: PrintReplaceFreq
  file_name: print_rep_freq_single
  class_name: PrintReplaceFreq
  label: PrintReplaceFreq
  description: ''
  tags: []
  libraries: []
  executors:
    name: ProcessExecutor
  inputs:
  - name: in_ds
    dataFlowType: series
    dataType: Any
    render_type: null
    default: null
    doc: null
    label: null
  outputs:
  - name: out_ds
    dataFlowType: series
    dataType: Any
    doc: null
    label: null
    transport:
      is_series:
      - true
      name: null
      topic: null
      sender_port: null
      receiver_port: null
      queue_size: 0
      has_initialized: false
  defaultExecutionMode: ProcessExecutor
  source:
    module_name: print_replace_freq_single
category: PrintReplaceFreqSingle
