bundle_name: IntType
description: null
version: 0.0.1
image: null
libraries: null
system_dependencies: null
environment: null
commands: null
blocks:
- name: Int
  file_name: integer
  class_name: IntType
  label: Int
  description: ''
  tags: []
  libraries: []
  executors:
    name: ProcessExecutor
  inputs:
  - name: a
    dataFlowType: atomic
    dataType: integer
    render_type: null
    default: 0
    doc: null
    label: null
  outputs: []
  defaultExecutionMode: ProcessExecutor
  source:
    module_name: IntType
category: Integer
