bundle_name: walmart_train
description: null
version: 0.0.1
image: null
libraries: null
system_dependencies: null
environment: null
commands: null
blocks:
- name: DataCreator3
  file_name: blocks
  class_name: DataCreator3
  label: DataCreator3
  description: ''
  tags: []
  libraries: []
  executors:
    name: ProcessExecutor
  inputs:
  - name: grid_path
    dataFlowType: atomic
    dataType: string
    render_type: null
    default: ''
    doc: null
    label: null
  - name: config
    dataFlowType: atomic
    dataType: json
    render_type: null
    default: {}
    doc: null
    label: null
  outputs:
  - name: grid_three_df_path
    dataFlowType: atomic
    dataType: string
    doc: null
    label: null
    transport:
      is_series:
      - false
      name: null
      topic: null
      sender_port: null
      receiver_port: null
      queue_size: 0
      has_initialized: false
  defaultExecutionMode: ProcessExecutor
  source:
    module_name: walmart_train
- name: Melter
  file_name: blocks
  class_name: Melter
  label: Melter
  description: ''
  tags: []
  libraries: []
  executors:
    name: ProcessExecutor
  inputs:
  - name: path
    dataFlowType: atomic
    dataType: string
    render_type: null
    default: ''
    doc: null
    label: null
  - name: config
    dataFlowType: atomic
    dataType: json
    render_type: null
    default: {}
    doc: null
    label: null
  outputs:
  - name: grid_df_path
    dataFlowType: atomic
    dataType: string
    doc: null
    label: null
    transport:
      is_series:
      - false
      name: null
      topic: null
      sender_port: null
      receiver_port: null
      queue_size: 0
      has_initialized: false
  defaultExecutionMode: ProcessExecutor
  source:
    module_name: walmart_train
- name: Train
  file_name: blocks
  class_name: Train
  label: Train
  description: ''
  tags: []
  libraries: []
  executors:
    name: ProcessExecutor
  inputs:
  - name: BASE
    dataFlowType: atomic
    dataType: Any
    render_type: null
    default: null
    doc: null
    label: null
  - name: PRICE
    dataFlowType: atomic
    dataType: Any
    render_type: null
    default: null
    doc: null
    label: null
  - name: CALENDAR
    dataFlowType: atomic
    dataType: Any
    render_type: null
    default: null
    doc: null
    label: null
  - name: LAGS
    dataFlowType: atomic
    dataType: Any
    render_type: null
    default: null
    doc: null
    label: null
  - name: MEAN_ENC
    dataFlowType: atomic
    dataType: Any
    render_type: null
    default: null
    doc: null
    label: null
  outputs: []
  defaultExecutionMode: ProcessExecutor
  source:
    module_name: walmart_train
- name: LagCreator
  file_name: blocks
  class_name: LagCreator
  label: LagCreator
  description: ''
  tags: []
  libraries: []
  executors:
    name: ProcessExecutor
  inputs:
  - name: grid_path
    dataFlowType: atomic
    dataType: string
    render_type: null
    default: ''
    doc: null
    label: null
  outputs:
  - name: lag_df_path
    dataFlowType: atomic
    dataType: string
    doc: null
    label: null
    transport:
      is_series:
      - false
      name: null
      topic: null
      sender_port: null
      receiver_port: null
      queue_size: 0
      has_initialized: false
  defaultExecutionMode: ProcessExecutor
  source:
    module_name: walmart_train
- name: DataConcatenation
  file_name: blocks
  class_name: DataConcatenation
  label: DataConcatenation
  description: ''
  tags: []
  libraries: []
  executors:
    name: ProcessExecutor
  inputs:
  - name: grid_df_path
    dataFlowType: atomic
    dataType: string
    render_type: null
    default: ''
    doc: null
    label: null
  - name: add_grid_path
    dataFlowType: atomic
    dataType: string
    render_type: null
    default: ''
    doc: null
    label: null
  - name: config
    dataFlowType: atomic
    dataType: json
    render_type: null
    default: {}
    doc: null
    label: null
  outputs:
  - name: grid_df_int_path
    dataFlowType: atomic
    dataType: string
    doc: null
    label: null
    transport:
      is_series:
      - false
      name: null
      topic: null
      sender_port: null
      receiver_port: null
      queue_size: 0
      has_initialized: false
  defaultExecutionMode: ProcessExecutor
  source:
    module_name: walmart_train
- name: Configs
  file_name: blocks
  class_name: Configs
  label: Configs
  description: ''
  tags: []
  libraries: []
  executors:
    name: ProcessExecutor
  inputs: []
  outputs:
  - name: config
    dataFlowType: atomic
    dataType: json
    doc: null
    label: null
    transport:
      is_series:
      - false
      name: null
      topic: null
      sender_port: null
      receiver_port: null
      queue_size: 0
      has_initialized: false
  defaultExecutionMode: ProcessExecutor
  source:
    module_name: walmart_train
- name: Encoder
  file_name: blocks
  class_name: Encoder
  label: Encoder
  description: ''
  tags: []
  libraries: []
  executors:
    name: ProcessExecutor
  inputs:
  - name: grid_path
    dataFlowType: atomic
    dataType: string
    render_type: null
    default: ''
    doc: null
    label: null
  outputs:
  - name: encoded_df_path
    dataFlowType: atomic
    dataType: string
    doc: null
    label: null
    transport:
      is_series:
      - false
      name: null
      topic: null
      sender_port: null
      receiver_port: null
      queue_size: 0
      has_initialized: false
  defaultExecutionMode: ProcessExecutor
  source:
    module_name: walmart_train
- name: ValidDataCreator
  file_name: blocks
  class_name: ValidDataCreator
  label: ValidDataCreator
  description: ''
  tags: []
  libraries: []
  executors:
    name: ProcessExecutor
  inputs:
  - name: path
    dataFlowType: atomic
    dataType: string
    render_type: null
    default: ''
    doc: null
    label: null
  - name: config
    dataFlowType: atomic
    dataType: json
    render_type: null
    default: {}
    doc: null
    label: null
  outputs:
  - name: add_grid_path
    dataFlowType: atomic
    dataType: string
    doc: null
    label: null
    transport:
      is_series:
      - false
      name: null
      topic: null
      sender_port: null
      receiver_port: null
      queue_size: 0
      has_initialized: false
  defaultExecutionMode: ProcessExecutor
  source:
    module_name: walmart_train
- name: DataCreator1
  file_name: blocks
  class_name: DataCreator1
  label: DataCreator1
  description: ''
  tags: []
  libraries: []
  executors:
    name: ProcessExecutor
  inputs:
  - name: grid_df_path
    dataFlowType: atomic
    dataType: string
    render_type: null
    default: ''
    doc: null
    label: null
  - name: config
    dataFlowType: atomic
    dataType: json
    render_type: null
    default: {}
    doc: null
    label: null
  outputs:
  - name: grid_pkl_path
    dataFlowType: atomic
    dataType: string
    doc: null
    label: null
    transport:
      is_series:
      - false
      name: null
      topic: null
      sender_port: null
      receiver_port: null
      queue_size: 0
      has_initialized: false
  defaultExecutionMode: ProcessExecutor
  source:
    module_name: walmart_train
- name: DataCreator2
  file_name: blocks
  class_name: DataCreator2
  label: DataCreator2
  description: ''
  tags: []
  libraries: []
  executors:
    name: ProcessExecutor
  inputs:
  - name: grid_path
    dataFlowType: atomic
    dataType: string
    render_type: null
    default: ''
    doc: null
    label: null
  - name: config
    dataFlowType: atomic
    dataType: json
    render_type: null
    default: {}
    doc: null
    label: null
  outputs:
  - name: grid_two_df_path
    dataFlowType: atomic
    dataType: string
    doc: null
    label: null
    transport:
      is_series:
      - false
      name: null
      topic: null
      sender_port: null
      receiver_port: null
      queue_size: 0
      has_initialized: false
  defaultExecutionMode: ProcessExecutor
  source:
    module_name: walmart_train
category: TRAIN
