bundle_name: walmart_infer
description: null
version: 0.0.1
image: null
libraries: null
system_dependencies: null
environment: null
commands: null
blocks:
- name: Infer
  file_name: blocks
  class_name: Infer
  label: Infer
  description: ''
  tags: []
  libraries: []
  executors:
    name: ProcessExecutor
  inputs:
  - name: path
    dataFlowType: atomic
    dataType: string
    render_type: null
    default: ''
    doc: null
    label: null
  outputs: []
  defaultExecutionMode: ProcessExecutor
  source:
    module_name: walmart_infer
category: INFER
