---
id: "a991dc5c-f920-4453-bf12-05da8625b0bd"
name: "SparkJupyterTest"
imageId: "3be48c40442c2d4475a997feba6572c0761961ec3457a6e71ba91b4b63125959"
addedBy: "94412f9b-9d88-4376-b0e6-0725c1cabe3b"
addedOn: "Mon Mar 22 09:35:10 GMT 2021"
updatedBy: "94412f9b-9d88-4376-b0e6-0725c1cabe3b"
updatedOn: "Mon Mar 22 09:35:10 GMT 2021"
buildImageReqd: false
base_image: "gcr.io/razorthink-gcp-pre-prod/aios-images:10.5.2"
base_image_version: "10.5.2"
base_image_libraries:
  triggeredOn: "2021-03-19 05:18:55.262"
  pip_packages:
  - name: "razor-api"
    version: "0.0.1"
  - name: "razor-fs"
    version: "0.0.1"
  - name: "razor-ds"
    version: "0.0.1"
  - name: "rzt-dl"
    version: "4.0.0"
  - name: "model-designer-parser"
    version: "4.0.0"
  - name: "razor-flow"
    version: "2.0.0"
  - name: "cloudpickle"
    version: ">=1.3.0"
  - name: "boto3"
    version: "<1.16"
  - name: "pandas"
    version: ">=1.1.4"
  - name: "pysftp"
    version: ">=0.2.9"
  - name: "requests"
    version: "==2.23.0"
  - name: "hdfs"
    version: ">=2.5.8"
  - name: "requests_kerberos"
    version: ">=0.12.0"
  - name: "typeguard"
    version: "==2.2.2"
  - name: "typing-extensions"
    version: ""
  - name: "pygit2"
    version: ">=1.2.1"
  - name: "azure-storage-blob"
    version: ">=12.5.0"
  - name: "google-cloud-storage"
    version: "==1.32.0"
  - name: "pyyaml"
    version: ">=5.3.1"
  - name: "pyzmq"
    version: ">=19.0.0"
  - name: "networkx"
    version: ">=2.4"
  - name: "pygraphviz"
    version: ">=1.5"
  - name: "pydot"
    version: ">=1.4.1"
  - name: "IPython"
    version: ">=7.13.0"
  - name: "altair"
    version: ">=4.1.0"
  - name: "scikit-learn"
    version: ">=0.22.1"
  - name: "scipy"
    version: "==1.4.1"
  - name: "tblib"
    version: ">=1.6.0"
  - name: "pyspark"
    version: "==3.0"
  - name: "SQLAlchemy"
    version: "==1.3.20"
  - name: "PyMySQL"
    version: "==0.10.1"
  - name: "snowflake-sqlalchemy"
    version: "==1.2.4"
  - name: "pyodbc"
    version: "==4.0.30"
  - name: "smart-open"
    version: "==4.1.2"
  - name: "fastapi"
    version: "==0.63.0"
  - name: "semantic_version"
    version: "==2.8.5"
  - name: "cx_Oracle"
    version: "==8.1.0"
  - name: "sasl"
    version: "==0.2.1"
  - name: "thrift"
    version: "==0.13.0"
  - name: "thrift_sasl"
    version: "==0.4.2"
  - name: "pyhive"
    version: "==0.6.3"
  - name: "impyla"
    version: "==0.16.3"
  - name: "flask"
    version: "==1.1.2"
  - name: "numpy"
    version: "==1.19.5"
  - name: "ipywidgets"
    version: "==7.6.3"
  - name: "walkdir"
    version: "==0.4.1"
  - name: "python-multipart"
    version: "==0.0.5"
  - name: "ipykernel"
    version: "==5.4.3"
  - name: "pynacl"
    version: "==1.4.0"
  - name: "watchdog"
    version: ""
  - name: "psutil"
    version: ""
  - name: "cloudpickle"
    version: ">=1.3.0"
  - name: "boto3"
    version: "<1.16"
  - name: "pandas"
    version: ">=1.1.4"
  - name: "pysftp"
    version: ">=0.2.9"
  - name: "requests"
    version: "==2.23.0"
  - name: "hdfs"
    version: ">=2.5.8"
  - name: "requests_kerberos"
    version: ">=0.12.0"
  - name: "typeguard"
    version: "==2.2.2"
  - name: "typing-extensions"
    version: ""
  - name: "pygit2"
    version: ">=1.2.1"
  - name: "azure-storage-blob"
    version: ">=12.5.0"
  - name: "google-cloud-storage"
    version: "==1.32.0"
  - name: "pyyaml"
    version: ">=5.3.1"
  - name: "pyzmq"
    version: ">=19.0.0"
  - name: "networkx"
    version: ">=2.4"
  - name: "pygraphviz"
    version: ">=1.5"
  - name: "pydot"
    version: ">=1.4.1"
  - name: "IPython"
    version: ">=7.13.0"
  - name: "altair"
    version: ">=4.1.0"
  - name: "scikit-learn"
    version: ">=0.22.1"
  - name: "scipy"
    version: "==1.4.1"
  - name: "tblib"
    version: ">=1.6.0"
  - name: "pyspark"
    version: "==3.0"
  - name: "SQLAlchemy"
    version: "==1.3.20"
  - name: "PyMySQL"
    version: "==0.10.1"
  - name: "snowflake-sqlalchemy"
    version: "==1.2.4"
  - name: "pyodbc"
    version: "==4.0.30"
  - name: "smart-open"
    version: "==4.1.2"
  - name: "fastapi"
    version: "==0.63.0"
  - name: "semantic_version"
    version: "==2.8.5"
  - name: "cx_Oracle"
    version: "==8.1.0"
  - name: "sasl"
    version: "==0.2.1"
  - name: "thrift"
    version: "==0.13.0"
  - name: "thrift_sasl"
    version: "==0.4.2"
  - name: "pyhive"
    version: "==0.6.3"
  - name: "impyla"
    version: "==0.16.3"
  - name: "flask"
    version: "==1.1.2"
  - name: "numpy"
    version: "==1.19.5"
  - name: "ipywidgets"
    version: "==7.6.3"
  - name: "walkdir"
    version: "==0.4.1"
  - name: "python-multipart"
    version: "==0.0.5"
  - name: "ipykernel"
    version: "==5.4.3"
  - name: "pynacl"
    version: "==1.4.0"
  - name: "watchdog"
    version: ""
  - name: "psutil"
    version: ""
  - name: "cloudpickle"
    version: ">=1.3.0"
  - name: "pyzmq"
    version: ">=19.0.0"
  - name: "networkx"
    version: ">=2.4"
  - name: "pydot"
    version: ">=1.4.1"
  - name: "boto3"
    version: ">=1.12.35"
  - name: "pysftp"
    version: ">=0.2.9"
  - name: "requests"
    version: ">=2.23.0"
  - name: "hdfs"
    version: ">=2.5.8"
  - name: "IPython"
    version: ">=7.13.0"
  - name: "altair"
    version: ">=4.1.0"
  - name: "tblib"
    version: ">=1.6.0"
  - name: "typeguard"
    version: ">=2.2.2"
  - name: "pynacl"
    version: ""
  - name: "pygit2"
    version: ">=1.2.1"
  - name: "watchdog"
    version: ""
  - name: "psutil"
    version: ""
  - name: "pyyaml"
    version: "==5.3.1"
  - name: "munch"
    version: "==2.5.0"
  - name: "typeguard"
    version: "==2.7.1"
  - name: "networkx"
    version: "==2.5"
  system_packages: []
  environment_variables:
  - id: null
    variable: "LD_LIBRARY_PATH"
    type: "String"
    value: "/usr/local/cuda/extras/CUPTI/lib64:/usr/local/cuda/lib64:"
    origin: null
    description: null
  - id: null
    variable: "LANG"
    type: "String"
    value: "C.UTF-8"
    origin: null
    description: null
  - id: null
    variable: "NODE_OPTIONS"
    type: "String"
    value: "NODE_OPTIONS --max_old_space_size=2048"
    origin: null
    description: null
  - id: null
    variable: "SHELL"
    type: "String"
    value: "/bin/bash"
    origin: null
    description: null
environment_variables: []
